name: Build draft preview
on:
  pull_request_target:
    branches: ['2025']
    types: [labeled, opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  build-preview:
    uses: curvenote/actions/.github/workflows/draft.yml@v1
    with:
      id-pattern-regex: '^scipy-2025-(?:[a-zA-Z0-9-_]{3,15})$'
      enforce-single-folder: true
      venue: scipy
      collection: '2025'
      kind: article
      path: papers/*
      exclude: papers/myst_template, papers/tex_template
      label: draft
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
