name: Publish all 2025 articles
on: workflow_dispatch
permissions:
  contents: write
jobs:
  publish:
    uses: curvenote/actions/.github/workflows/submit.yml@v1
    with:
      id-pattern-regex: '^scipy-2025-(?:[a-zA-Z0-9-_]{3,25})$'
      venue: scipy
      collection: '2025'
      kind: article
      path: papers/*
      exclude: papers/myst_template, papers/tex_template
      include-unchanged: true
      publish: true
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
